FROM node:20-alpine AS base
WORKDIR /app

FROM base AS deps
COPY package.json package-lock.json ./
RUN npm ci

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_API_COURSES
ARG NEXT_PUBLIC_API_DESAFIOS
ARG NEXT_PUBLIC_API_LICOES
ARG NEXT_PUBLIC_API_OPCOES_DESAFIOS
ARG NEXT_PUBLIC_API_PROGRESO_DESAFIOS
ARG NEXT_PUBLIC_API_SUBSCRIPTION
ARG NEXT_PUBLIC_API_UNIDADES
ARG NEXT_PUBLIC_API_USUARIO

ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_API_COURSES=$NEXT_PUBLIC_API_COURSES
ENV NEXT_PUBLIC_API_DESAFIOS=$NEXT_PUBLIC_API_DESAFIOS
ENV NEXT_PUBLIC_API_LICOES=$NEXT_PUBLIC_API_LICOES
ENV NEXT_PUBLIC_API_OPCOES_DESAFIOS=$NEXT_PUBLIC_API_OPCOES_DESAFIOS
ENV NEXT_PUBLIC_API_PROGRESO_DESAFIOS=$NEXT_PUBLIC_API_PROGRESO_DESAFIOS
ENV NEXT_PUBLIC_API_SUBSCRIPTION=$NEXT_PUBLIC_API_SUBSCRIPTION
ENV NEXT_PUBLIC_API_UNIDADES=$NEXT_PUBLIC_API_UNIDADES
ENV NEXT_PUBLIC_API_USUARIO=$NEXT_PUBLIC_API_USUARIO

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app

RUN addgroup -S -g 1001 appgroup && adduser -S -u 1001 -G appgroup appuser

ENV NODE_ENV=production
ENV PORT=3000
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=builder --chown=appuser:appgroup /app/.next/standalone ./
COPY --from=builder --chown=appuser:appgroup /app/.next/static ./.next/static
COPY --from=builder --chown=appuser:appgroup /app/public ./public

USER appuser
EXPOSE 3000
CMD ["node", "server.js"]